/**
 * Assemble the ordered native workbench sources into one internal ESM bundle.
 * The files intentionally share one scope; changing the order is a breaking change.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDirectory, "..");
const sourceRoot = join(packageRoot, "src");
const outputDirectory = join(packageRoot, "dist");
const outputPath = join(outputDirectory, "index.js");

const sourceFiles = [
  "js/utils.js",
  "js/state.js",
  "js/parser.js",
  "js/content.js",
  "js/json-importer.js",
  "js/validator.js",
  "js/renderer.js",
  "js/editor.js",
  "js/persistence.js",
  "js/exporter.js",
  "js/overflow.js",
  "js/photo.js",
  "js/app.js",
];

const sampleFilename = "sample-resume.md";
const requiredFiles = [
  ...sourceFiles.map((file) => join(sourceRoot, file)),
  join(packageRoot, "fixtures", "valid", sampleFilename),
  join(sourceRoot, "template.html"),
  join(sourceRoot, "styles", "app.css"),
  join(sourceRoot, "styles", "resume.css"),
  join(sourceRoot, "styles", "print.css"),
];

const missingFiles = requiredFiles.filter((file) => !existsSync(file));
if (missingFiles.length > 0) {
  throw new Error(`resume-workbench source files are missing:\n${missingFiles.join("\n")}`);
}

const sampleMarkdown = readFileSync(
  join(packageRoot, "fixtures", "valid", sampleFilename),
  "utf8",
);
const source = [
  "// Generated by scripts/build.mjs. Do not edit dist directly.",
  'import { adaptResumeContent, parseResumeContentV3, RESUME_PROFILE_FIELDS } from "web-contracts/resume-document";',
  `const DEFAULT_RESUME_MD = ${JSON.stringify(sampleMarkdown)};`,
  `const DEFAULT_RESUME_FILENAME = ${JSON.stringify(sampleFilename)};`,
  ...sourceFiles.map((file) => `// ${file}\n${readFileSync(join(sourceRoot, file), "utf8")}`),
  "export { startWorkbench, loadDocument, readDocument, isDirty, clearDirty };",
  "",
].join("\n\n");

rmSync(outputDirectory, { recursive: true, force: true });
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(outputPath, source, "utf8");

const syntaxCheck = spawnSync(process.execPath, ["--check", outputPath], {
  encoding: "utf8",
});
if (syntaxCheck.status !== 0) {
  process.stderr.write(syntaxCheck.stderr || syntaxCheck.stdout);
  process.exit(syntaxCheck.status || 1);
}

console.log(`Built ${outputPath}`);
